In [1]:
import numpy as np
import pandas as pd
import math as m
import cmath
import sympy as sym
import scipy as sci
import matplotlib.ticker as ticker
import random as rand
import matplotlib.pyplot as plt
import cmath as cm
from IPython.display import display, Latex
from sympy import pprint
# from scipy.optimize import minimize as GDlib
from scipy.optimize import minimize 
import MLE_functions_numpy as fn
from MLE_functions_numpy import *
from scipy.optimize import fsolve
import pandas as pd
import MLE_functions_numpy as fnn
# from minimize import least_squares

explicitly writing all the intermediate values in the inversion function to spot the error in fidelities..

the error is narrowed down to difference in the theoretical numerical density matrices which comes from num experiment function. 
exploring it below

In [ ]:
states_tru2 = fnn.Creating_states(tru2)
expt = fnn.num_experiment(params = tru2, nju = bad_nju)


st_1 = states_tru2[0]
# st_2 = expt[0]

stst = states_tru2[1]

print('','rho_th:',)
rho = states_tru2[2]
print(rho)

r = expt[1]
r_n = expt[2]
p = expt[3]
n = expt[4]



FixED!! Moving back to debugging the inversion function, , specifically the problem of possibile flipping of the coefficients

So apparently the error turns out to be in the order of elements of the eigenvector of concern which is the xi eigenvector and apparently the first and the second elements are flipped for that we expect the un flipped versions because the reason that very small perturbation from the actual theoretical matrix should only result in a small perturbation in the eigenvectors and not a huge one as it seems to be

trying many collapse vectors at random and seeing for how many of them the Xi vector is "inverted" in the corresponding coeffs and fids. 

Checking likelihood function for bad njus

In [ ]:
tru6 = [m.pi/2+m.pi/12, m.pi/2+ m.pi/6, 0, m.pi/2, m.pi/12]
coll6 = fnn.generate_collapses(tru6, 5000, 100)

for i in coll6:
    err4_i = fnn.ppm_errors(tru6, i)
    if sum(err4_i[0])>400000:
        print('more', err4_i)
        print('more', i)
    if sum(err4_i[0])<30000:
        print('less!', err4_i)
        print('less', i)


# more [[1083.1074292144694, 598711.0534063264], [1928.8616851780293, 619300.2918287966]]
# [[1258.3445740775855, 951200.5509476968], [462.0747215567933, 951200.5509476968]]
# [[840.6540047416478, 749944.5203257491], [898.3376353625116, 765841.7839133753]]

bnj1 = [1307, 144, 712, 473, 103, 756, 612, 133, 760]
bnj2 = [1444, 148, 617, 519, 95, 777, 600, 123, 677]
bnj3 = [1342, 169, 667, 490, 99, 750, 594, 103, 786]
less1= [1366, 148, 654, 511, 89, 760, 619, 126, 727]
[1339.3, 161.928, 638.95, 525.47, 91.883, 753.33, 614.28, 121.488, 753.3386257884266]

[i*5000 for i in fnn.pr_num(tru6)]

In [ ]:
# testing likelihood functions for the abobve bad values
L1_m = fnn.L(vars = False, n = bnj1)
L1 = fnn.L(vars = tru6, n = bnj1)

# do same for following

# [[0.0, 957209.8391575121], [733.1377895182234, 856342.752447464]]
# [645, 6, 650, 619, 4, 697, 706, 7, 666]

# [[0.0, 981256.4527567336], [62.809710090316884, 829699.8641764291]]
# [666, 7, 683, 645, 4, 649, 668, 9, 669]

# less! [[0.0, 6852.582189213807], [60756.135037916545, 146949.14959349524]]
# less [661, 4, 631, 661, 7, 671, 681, 3, 681]


L2_m = fnn.L(vars = False, n = bnj2)
L2 = fnn.L(vars = tru6, n = bnj2)

L3_m = fnn.L(vars = False, n = bnj3)
L3 = fnn.L(vars = tru6, n = bnj3)



print([L1_m, L1])
print([L2_m, L2])
print([L3_m, L3])


In [ ]:
fnn.ppm_errors(tru6, [1307, 144, 712, 473, 103, 756, 612, 133, 760])

prams1 = [1.33073649+0.00000000e+00j,  0.17024566+0.00000000e+00j,2.9826044 +0.00000000e+00j, -0.93498342+0.00000000e+00j,0.21936886-1.21965119e-17j]


bnj1 = [1307, 144, 712, 473, 103, 756, 612, 133, 760]
bnj2 = [1444, 148, 617, 519, 95, 777, 600, 123, 677]
bnj3 = [1342, 169, 667, 490, 99, 750, 594, 103, 786]
less1= [1366, 148, 654, 511, 89, 760, 619, 126, 727]

# fun = fnn.L(vars = prams1, n = bnj1)
# fun

L_tru6 = fnn.L(vars = tru6, n = bnj1)
print(L_tru6)

# MARTIN CASE
# opt.AuxParams={{0.2614,0.0288,0.1424,0.0946,0.0206,0.1512,0.1224,0.0266,0.152}}
# case6(MIT): {theta1,theta2,phi1,phi2,alpha}={{1.33073649,0.17024566,-2.9826044,-0.93498342,0.21936886}}
#  ---> NYFunction = 1.959768143157167
bnjn1 = [i/sum(bnj1) for i in bnj1]
prob_params = fnn.pr_num([1.33073649,0.17024566,-2.9826044,-0.93498342,0.21936886])
prob_params = [0.25526472341208967, 0.02896871461128489, 0.1333327431548282, 0.0969470432734706, 0.020183709309324616, 0.15304763238431282, 0.1239280379744138, 0.026836900566235833, 0.16149049531404092]
log_prob_params = [m.log(i) for i in prob_params]
L_list = [m.log(i)*j for i,j in zip(prob_params, bnjn1)]
L = sum(L_list)
L

# fucntion output
Lf = fnn.L(vars = [1.33073649,0.17024566,-2.9826044,-0.93498342,0.21936886], n = bnj1)
Lf

In [ ]:
a = [0.17050398243083,4.4722844667216,5.3576515384017,3.3006005582285,1.7900422339236]
fn.fid([a[1],a[0],a[3],a[2],a[4]], tru6)

# [[1083.1074292144694, 598711.0534063264], [1928.8616851780293, 619300.2918287966]]

In [ ]:
orig = 

In [ ]:
def CheckingCMatrix(index = [0,0], psi = [1,0], psi2 = [0,1], p = [.5,.5]):
    sigma_x = np.array([[0, 1], [1, 0]])    # 2d matrices in the comp  basis
    sigma_y = np.array([[0, -1j], [1j, 0]])
    sigma_z = np.array([[1, 0], [0, -1]])
    
    matrices = np.array([sigma_x, sigma_y, sigma_z])
    # print('list paulis=\n', matrices)

    R_matrix = (1/np.sqrt(2))*np.array([[np.sqrt(2),0,0,0],[0,1,-1,0],[0,1,1,0],[0,0,0,np.sqrt(2)]])
    R_matrix_inverse = np.linalg.inv(R_matrix) 
    sigma_x_tilda_comp = np.kron(sigma_x , np.identity(2))
    sigma_y_tilda_comp = np.kron(sigma_y , np.identity(2))
    sigma_z_tilda_comp = np.kron(sigma_z , np.identity(2))
    sigma_x_tilda = np.dot(np.dot(R_matrix ,sigma_x_tilda_comp), R_matrix_inverse)
    sigma_y_tilda = np.dot(np.dot(R_matrix ,sigma_y_tilda_comp), R_matrix_inverse)
    sigma_z_tilda = np.dot(np.dot(R_matrix ,sigma_z_tilda_comp), R_matrix_inverse)

    tensor_sigma_ij_comp = np.kron(matrices[index[0]], matrices[index[1]])
    print(f"\ntensor_sigma_comp_{index}\n",tensor_sigma_ij_comp)

    tensor_sigma_ij_tilda = np.dot(np.dot(R_matrix, tensor_sigma_ij_comp), R_matrix_inverse)
    print(f"\ntensor_sigma_{index}_tilda\n",tensor_sigma_ij_tilda)
    
    rho1_comp = np.outer(np.kron(psi, psi),np.kron(psi, psi))
    rho2_comp = np.outer(np.kron(psi2, psi2),np.kron(psi2, psi2))
    rho1_tilda = np.dot(np.dot(R_matrix ,rho1_comp), R_matrix_inverse)
    rho2_tilda = np.dot(np.dot(R_matrix ,rho2_comp), R_matrix_inverse)

    rho_mixed_comp = p[0]*rho1_comp + p[1]*rho2_comp
    rho_mixed_tilda = p[0]*rho1_tilda + p[1]*rho2_tilda


    print("\n rho_1_comp = \n", rho1_comp)
    print("\n rho_2_comp = \n", rho2_comp)
    print("\nrho_mixed_comp = \n", rho_mixed_comp)
    print("\nrho_mixed_tild = \n", rho_mixed_tilda)

    C_ij = np.trace(np.dot(tensor_sigma_ij_tilda, rho_mixed_tilda))
    print(f" \nElement C_{index}\n", C_ij)

    
    # print(f"tensor_sigma_{index}_tilda\n",tensor_sigma_ij_tilda)



# CheckingCMatrix()
# CheckingCMatrix(psi = [.5, np.sqrt(3)/2], psi2= [ np.sqrt(3)/2, .5], index = [2,2]) # using the rotation method of change of basis

In [ ]:

w = m.e**((2/3)*m.pi*(1j))     # third root of unity
POVM_vec = (1/(2**.5))*(np.array([[0,1,-1],[-1,0,1],[1,-1,0],[0,w,-w**2],[-1,0,w**2],[1,-w,0],[0,w**2,-w],[-1,0,w],[1,-w**2,0]]))  # an array of POVM direction vectors
POVM_elts = [(1/3)*np.outer(np.conjugate(POVM_vec[i]),POVM_vec[i]) for i in range(len(POVM_vec))]   # a list of POVM matrices
M = [[np.trace(np.dot(POVM_elts[i],POVM_elts[j])) for i in range(len(POVM_elts))] for j in range(len(POVM_elts))]     # creating M matrix using POVM definition
u_0 = [1/3 for i in range(9)]           # cerating u_0 vector, to create the inverse matrix
M_inv = 3*np.outer(u_0,u_0) + 12*(np.eye(9) - np.outer(u_0,u_0))        # creating the inverse matrix


def num_experiment(N = 10000, params = [0,m.pi/2,0,0,m.pi/4], show_calcs = False, seed = None):
    creation = fn.Creating_states( params = params, Abstract = 0) # theoretical rho
    states = creation[0]
    sq_states = creation[1]
    rho = creation[2]
    # print(rho)
    # print(states)
    prob_vec_sympy_0 =  [np.trace(np.dot(POVM_elts[i],rho)) for i in range(9)]    # created list of Th probabilities
    prob_vec_sympy = [i.evalf() for i in prob_vec_sympy_0]  # evaluated the sympy expressions
    prob_vec = [np.complex64(i) for i in prob_vec_sympy]  # converted to regular complex numbers
    # prob_vec_raw = [(float(i.as_real_imag()[0])+float(i.as_real_imag()[1])*1j) for i in prob_vec_sympy]  # this is to avoid error, to convert sympy float to ordinary number
    # prob_vec = [round(i.real, 10) for i in prob_vec_raw if abs(i.imag) < .0001]          # cleaned up theoretical prob vector
    # prob_vec = prob_vec_sympy
    
    print('rho\n')
    pprint(rho)
    print('prob_vec_sympy_0\n', prob_vec_sympy_0)
    print('prob_vec_sympy\n', prob_vec_sympy)
    print('prob_vec\n', prob_vec)
    print('prob_vec\n', prob_vec)
    print('sum prob_vec\n', sum(prob_vec))
    # print('prob_vec_raw\n', prob_vec_raw)    

    POVM_dir_symbols = ['d1','d2','d3','d4','d5','d6','d7','d8','d9']      # symbols to indicate collapsed direction
    #prob distribution is simply the corresponding elements of the prob_vec
    collapse_dir_vec = rand.choices(POVM_dir_symbols, weights=prob_vec, k = N)   # choosing collapse directions with weights for N trials
    nj_vec = [collapse_dir_vec.count(f'd{i+1}') for i in range(9)]
    pj_num_vec = [i/N for i in nj_vec]                                  # numerical prob vector     

    r_vec = np.dot(M_inv,pj_num_vec)
    rho_num_list = [r_vec[i]*POVM_elts[i] for i in range(len(POVM_elts))]   # list of matrices, see equation 7 in notes pair_disc.pdf
    rho_num = np.zeros_like(rho_num_list[0])
    # Loop for reconstructing the numerical matrix
    for i in rho_num_list:
        rho_num = np.add(rho_num, i)
    

    
    return [states, rho, rho_num, prob_vec, nj_vec]


In [ ]:
# params_i = [.1, m.pi/2+.1, .1, .1, m.pi/4+.1]
params_i = [0, m.pi/2+.1, .1, .1, m.pi/4]
nj_unnorm = num_experiment(params= params_i, N = 10000)[4]


In [ ]:
# debugging the complex probabilities


def num_experiment(N = 10000, params = [0,m.pi/2,0,0,m.pi/4], seed = None, an_pr = False):
    if seed is not None:
        rand.seed(seed)
    
    creation = fn.Creating_states( params = params, Abstract = 0) # theoretical rho
    states = creation[0]
    sq_states = creation[1]
    rho = creation[2]
    # print(rho)
    # print(states)
    prob_vec_sympy =  [np.trace(np.dot(fn.POVM_elts[i],rho)) for i in range(9)]    # created list of Th probabilities
    prob_vec_raw = [(float(i.as_real_imag()[0])+float(i.as_real_imag()[1])*1j) for i in prob_vec_sympy]  # this is to avoid error, to convert sympy float to ordinary number
    prob_vec = [round(i.real, 10) for i in prob_vec_raw if abs(i.imag) < .0001]          # cleaned up theoretical prob vector
    if an_pr == True:
        prob_vec = [i.subs({fn.theta1: params[0], fn.theta2: params[1], fn.phi1:params[2], fn.phi2: params[3], fn.alpha: params[4]}) for i in fn.pr]  # using prof hillery's analytic probabilities
        prob_vec = [round(i.evalf(), 12) for i in prob_vec]

    POVM_dir_symbols = ['d1','d2','d3','d4','d5','d6','d7','d8','d9']      # symbols to indicate collapsed direction
    #prob distribution is simply the corresponding elements of the prob_vec
    collapse_dir_vec = rand.choices(POVM_dir_symbols, weights=prob_vec, k = N)   # choosing collapse directions with weights for N trials
    nj_vec = [collapse_dir_vec.count(f'd{i+1}') for i in range(9)]
    pj_num_vec = [i/N for i in nj_vec]                                  # numerical prob vector     

    r_vec = np.dot(fn.M_inv,pj_num_vec)
    rho_num_list = [r_vec[i]*fn.POVM_elts[i] for i in range(len(fn.POVM_elts))]   # list of matrices, see equation 7 in notes pair_disc.pdf
    rho_num = np.zeros_like(rho_num_list[0])
    # Loop for reconstructing the numerical matrix
    for i in rho_num_list:
        rho_num = np.add(rho_num, i)
    
    return [states, rho, rho_num, prob_vec, nj_vec]


In [ ]:
#write a code to create random lists of 5 integers and use the prnum function, then sum it and then only add to the list if it exceeds 1.
error_p = []
error_params = []
for i in range(1000000):
    p_i = np.random.rand(5)*m.pi
    probs_list = [i(*p_i) for i in pr_num]   
    if sum(probs_list) > 1+ 1e-14 or sum(probs_list) < 1-1e-14:
        print(sum(probs_list))
        print(probs_list)
        error_p.append(probs_list)
        error_params.append(p_i)
print(error_p)
print(error_params)
# Here we checked randomly at 10 million points in the parameter space to find anomalies in the probability sum 
# but it is summing out to be correct up to 14 digits after 1

testing the newly converted functions from simpy to numpy

In [ ]:
tru2
# parameters for two orthogonal states
params = [0, m.pi/2, 0, 0, m.pi/4]
params1 = [0,m.pi/4, 0, m.pi, m.pi/4]


fnn.Creating_states(params1)

In [ ]:
fnn.fid([0, m.pi/2, 0, m.pi/2, m.pi/12], [0, m.pi/2+m.pi/12, 0, 0, m.pi/4]) 

# np.cos(m.pi/12)**2

## Checking for errors:
*similar parameters yet almost zero fidelity

*anomalous cases when cross entropy is lesser than the theoretical minimum using inversion but not with random ig

*finally matching Martin's results with my own

In [2]:
# studying the case of tru2 : [m.pi/4, m.pi/2+m.pi/4, m.pi/2, m.pi/4, m.pi/3]

tru2 = [m.pi/4, m.pi/2+m.pi/4, m.pi/2, m.pi/4, m.pi/3]
nju2 = [1856,1834,1073,660,646,204,1236,1260,1231]
print(10000- sum(nju2))

# generated = fnn.generate_collapses(tru2, 10000, 50)
nju2 = [i for i in generated]


0


In [4]:
# print(nju2[0]) = [1860, 1910, 1066, 598, 648, 165, 1240, 1247, 1266]
Creating_states(tru2)[0]

[array([7.07106781e-01+0.j        , 4.32978028e-17+0.70710678j]),
 array([-0.70710678+0.j ,  0.5       +0.5j])]

In [5]:
for i in nju2[:10]:
    invi = Inversion_new(params = tru2, nju = i)[0]
    print(invi)
   

[[0.001621332715412257, 0.5039337238407889], [0.001621332715412257, 0.5039337238407889], [0.998378667284588, 0.9999569841103259]]
[[0.0008576103473373196, 0.4926826095126917], [0.0008576103473373196, 0.4926826095126917], [0.9991423896526629, 0.9999148564975148]]
[[0.0005872727100009974, 0.5062914615775588], [0.0005872727100009974, 0.5062914615775588], [0.9994127272899992, 0.9998795031076952]]
[[0.0001551487749326387, 0.49023252189205385], [0.0001551487749326387, 0.49023252189205385], [0.9998448512250676, 0.9998458066963108]]
[[0.0018993303113960024, 0.48229664660237487], [0.0018993303113960024, 0.48229664660237487], [0.9981006696886043, 0.9996493028098142]]
[[0.003516664497429081, 0.5033739138205914], [0.003516664497429081, 0.5033739138205914], [0.996483335502571, 0.9999878672360709]]
[[0.00015728829407566925, 0.498725141293852], [0.00015728829407566925, 0.498725141293852], [0.9998427117059244, 0.999616401756475]]
[[0.002259690767393755, 0.5032928758829355], [0.002259690767393755, 0.50

In [10]:
# print('','\n\n',)
#optimizing emthod
for i in nju2[:10]:
    opti = minimize(L, np.random.rand(5) , method = 'CG' , args=(i))
    fids = fnn.fid(params1 = opti.x, params2 = tru2)
    print(fids)
    print(opti.x,'\n')



[0.14671238445955506, 0.11994740734108675]
[-0.78761211  0.79635775  0.78465651  1.49243841  2.61740678] 

[0.14306832085512805, 0.16192579731736945]
[2.35558587 0.78065019 0.7950004  1.61363081 0.53632328] 

[0.9997515912633246, 0.9998645856323716]
[0.78143615 0.77438436 1.54028491 3.91947577 1.04928814] 

[0.9999732663077293, 0.9998661251956923]
[ 0.78495861 -0.79489586  1.56049279  0.79861629  1.03798549] 

[0.9985749381535893, 0.9995178115174796]
[0.77740212 0.78637938 1.64460469 3.97086809 1.0476849 ] 

[0.1512165855241088, 0.14543991464392392]
[2.35208747 0.84602317 0.77202888 1.56047841 0.52269185] 

[0.1433127998756536, 0.13628934699494316]
[0.76799783 0.78170454 3.93651125 1.54160912 0.53607659] 

[0.9995063584676622, 0.9999407590368977]
[-3.94742493  2.34887273 -1.55333642  0.79014553  1.03662586] 

[0.14269044196823155, 0.14753568731403888]
[-0.78615617  0.80090307  0.79608063  1.57339382  0.5211543 ] 

[0.14374823019575778, 0.14001306284297316]
[2.35145783 0.75193492 7.0762

In [19]:
# fnn.fid([2.38600916, 5.50206473, -1.57852381, 0.80655743, 1.05913538], tru2)
# eg. bad:  [-0.78600608  0.78063878  0.7949682   1.613528   -0.53631765] , [0.14307959656473784, 0.1618880028045859]
fnn.fid( [-0.78600608 , 0.78063878  ,0.7949682  , 1.613528   ,-0.53631765] , tru2)
